### ISSUE TITLE
Cannot use classes

### ISSUE THREAD

**Issue by umdstu** [ruffythepirate/ts-geometry-2d#1]
Hi there,

I just stumbled upon your library and it looks really clean, thank you for sharing this with the public.

Unfortunately when I tried to use the package, I get an error:

`Constructor of class 'Polygon' is private and only accessible within the class declaration.`

I tried importing like:
`import {LineSegment, Polygon} from "ts-2d-geometry";`
and also separately in case tree shaking wasn't working:
```
import {Polygon} from "ts-2d-geometry/dist/Polygon";
import {LineSegment} from "ts-2d-geometry/dist/LineSegment";
```
and lastly I tried
`import * as geo from "ts-2d-geometry"`

I've never had this problem before so I'm unsure what I could be doing wrong.

Thanks!

**Comment by umdstu** [comment]
It seems like you intended the class to only be used via the `.fromPoint()` function, in which case this should be somewhat expected behavior. LineSegment works as expect though.

**Comment by ruffythepirate** [comment]
Hi @umdstu,

Thanks for your feedback, I'm really happy to hear that you've liked it so far!

Your observation is correct, `.fromPoints()` is the intended method to use. The inconsistency is rather that I had forgotten to make the `LineSegment` constructor private. 

The reason why I preferred using the static method for these classes is that during development I found that it wasn't obvious what parameters was best to use for the constructor, and then using the static method on the class gives the advantage of more verbosely explaining what is expected if somebody would be working with pure Javascript.
