### ISSUE TITLE
Link to GitHub repository

### ISSUE THREAD

**Issue by axelpale** [ruffythepirate/ts-geometry-2d#11]
Great lib! Unfortunate that a possible user like me is having a rough time when trying to navigate to the GitHub repository of the project where all the magic happens.

This hardship is due to:
- users land on the project's NPM page after searching via Google or NPM
- package.json lacks [repository property](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository) and therefore [NPM](https://www.npmjs.com/package/ts-2d-geometry) is unable to show a link to the repo.
- README.md lacks a link both to the github and npm. It only links to the GitHub Pages where the documentation, in similar manner, does not have a clear hyperlink to the repository nor the NPM page.

I believe by fixing these navigational issues people would find the lib much easier and accessible.

**Comment by ruffythepirate** [comment]
Hey @axelpale, 

I'm really happy to hear that you liked it and thank you for the good points! Your feedback makes a lot of sense, it's a bit confusing because I unfortunately created the npm package with the name `ts-2d-geometry` and the git project as `ts-geometry-2d`. Anyway, I've fixed the documentation according to your suggestion as part of release 6.3.2

**Comment by axelpale** [comment]
Wow, that was fast, great :)

Ah, that explains why I could not find the repo at github.com/ruffythepirate/ts-2d-geometry. I think it is not a big issue but if the difference bugs you and you would like to correct it, GitHub handles repository name changes quite nicely by automatically setting up permanent URL redirections from the old name to the new name.

FYI, I mentioned ts-geometry-2d in my review on [2D geometry libraries for JavaScript](https://www.akselipalen.com/2021/06/10/2d-geometry-libraries-for-javascript/). Cheers!
