### ISSUE TITLE
Coordinate system details

### ISSUE THREAD

**Issue by axelpale** [ruffythepirate/ts-geometry-2d#12]
The README has following sentence:

> The library assumes a coordinate system where positive x goes to the right, and positive y goes to the left.

I assume it should end with 

> ... and positive y goes to the bottom.

or

> ... and positive y goes down.

or top or up, depending what was meant by the sentence originally.

**Comment by ruffythepirate** [comment]
That's a good point, had to dig into the code myself to see what made sense. Now it's corrected (the answer was up :) )
