### ISSUE TITLE
Polygon Creation issue

### ISSUE THREAD

**Issue by umdstu** [ruffythepirate/ts-geometry-2d#3]
Good morning again,

I think I may have come across a little bug that took me much too long to come to a conclusion on. I think it boils down to a Polygon, given 4 points, doesn't create an enclosed area every time. For the sake of brevity i'll include two screenshots so i hopefully don't have to type everything out. You'll see the polygon should be a rectangular shape, but the polygon segments generated are... wrong.

Let me know your thoughts, if it's what i'm thinking, i'm sure it'll be obvious.

Sample grid with points (that make up the polygon) and the segment:
![gridcapture](https://user-images.githubusercontent.com/1298036/88682127-52d1c980-d0c0-11ea-9b8d-cbe3f8079a64.PNG)

The code:
![code](https://user-images.githubusercontent.com/1298036/88682378-9a585580-d0c0-11ea-8e71-024ef85b3d14.PNG)

The console output:
![console debug](https://user-images.githubusercontent.com/1298036/88682217-6da43e00-d0c0-11ea-8442-963fc7b55235.PNG)

If I swap some of the points around in the `fromPolygon()` function, sometimes you get 1 intersection (almost there) and other times still 0, but still not the 2 desired.

Thanks

**Comment by ruffythepirate** [comment]
Hi @umdstu ,

that's a good catch, thank you! It was a numerical floating point issue that has been fixed now (release 2.0.2). In addition I have clarified how the polygon needs to be constructed (points need to be given that define lines that doesn't intersect each other), not adhering to this will now throw an exception release 2.0.3, and documentation was improved in 2.0.4.

So try it out, version 2.0.4 is out on npm now, please try it out :)

**Comment by umdstu** [comment]
Thanks for the quick turn around on that and the updated documentation!
